### ISSUE TITLE
Webworker

### ISSUE THREAD

**Issue by Extarys** [neneos/nuxt-highlight.js#1]
It would be nice if someone eventually add the webworker functionality
https://highlightjs.org/usage/

thank you for this

**Comment by RobinSoenen** [comment]
Hello,

This is just a wrapper around vue-highlightjs (https://github.com/metachris/vue-highlightjs).
Feel free to add an issue on their repo.
When they add it I'll be happy to update this package.

kr,

Robin

**Comment by Extarys** [comment]
Oh sorry! Thanks
